package el.dv.fayucafinder.util

object Const {
    // Map Constants
    const val CITY_SELECTION_ZOOM_LEVEL = 10f
    const val CURRENT_LOCATION_SELECTION_ZOOM_LEVEL = 14f

    // Notification Constants
    const val FAYUCA_FINDER_MAIN_NOTIFICATION_CHANNEL_ID = "FAYUCA_FINDER_MAIN_NOTIFICATION_CHANNEL_ID"
    const val FAYUCA_FINDER_MAIN_NOTIFICATION_CHANNEL_NAME = "Fayuca Finder Notifications"
    const val FAYUCA_FINDER_PERMISSION_NOTIFICATION_CHANNEL_ID = "FAYUCA_FINDER_PERMISSION_NOTIFICATION_CHANNEL_ID"
    const val FAYUCA_FINDER_PERMISSION_NOTIFICATION_CHANNEL_NAME = "Fayuca Finder Permission Notifications"
    const val FAYUCA_FINDER_NOTIFICATION_PERMISSION_ID = 1515
}
